# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 02:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_goods'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=20, unique=True)),
                ('password', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=50)),
                ('tel', models.CharField(max_length=20)),
                ('address', models.CharField(max_length=100)),
                ('img', models.CharField(max_length=50)),
                ('rank', models.CharField(max_length=10)),
                ('token', models.CharField(max_length=256)),
            ],
            options={
                'db_table': 'axf-user',
            },
        ),
    ]
