# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-05 07:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_auto_20181105_1417'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='tel',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
